### ISSUE TITLE
Error while update the client on macOS

### ISSUE THREAD

**Issue by manudisaster** [kaiserdj/Darkorbit-client#28]
[
<img width="922" alt="Schermata 2021-05-28 alle 07 55 05" src="https://user-images.githubusercontent.com/46319741/119937171-9ae4a580-bf8a-11eb-8315-dff1d62e8d11.png">
](url)

**Comment by kaiserdj** [comment]
Apple, among several of its regulations for developers, forces you to pay $ 99 for them to consider you from their official developer program and to be able to sign applications.

Since this is a free application and I do not make any money from it, I will not pay this money.

For what Mac users, it will give them this error when updating and what you have to do is enter github and manually download the latest version of the launcher.

More information about this: https://developer.apple.com/support/compare-memberships/


Sorry about these problems, but there is nothing I can do to fix it
