### ISSUE TITLE
Unable to run Pepperflash Player

### ISSUE THREAD

**Issue by mikefi2** [kaiserdj/Darkorbit-client#61]
Hi guys! New to github. Try to run the darkorbit-client. I have installed the latest java given. run the npm install from the command promt. App started ok. I've logged in to my account. Any ideas on how to install your flash player? Thanks in advance. Mike

**Comment by kaiserdj** [comment]
Good afternoon Mike,

You don't need to install flash since it's built into the browser, and you don't need to use npm either. In this link you have available the latest compiled version of the client https://github.com/kaiserdj/Darkorbit-client/releases

It depends on which operating system you use, you have to download one file or another.

Any questions, tell me.

Thank you very much and greetings

**Comment by kaiserdj** [comment]
The issue is closed due to lack of information. If you wish to provide more information or any other type of comment, do not hesitate to reopen the issue.
