### ISSUE TITLE
Open shop URLs in external browser

### ISSUE THREAD

**Issue by Ionic97** [kaiserdj/Darkorbit-client#9]
Shop links open in the same session and are not fully compatible.

**Comment by kaiserdj** [comment]
Can you tell me the exact places where you have problems or what steps to follow?

**Comment by Ionic97** [comment]
Using Windows 10:

So there are two ways to shop:
1. from the game window
2. from the client window

Description
1. are things like the shop symbol or the uridium bank. In case of the uridium bank it just uses the window you're playing in and opens the shop page (which works so far). This is bad, due to it "killing" the game instance. It would be better if it opens in an external browser. The shop symbol opens the shop in a separate popup. This is good! But it would be still better if it would open in an external browser (due to issues with some payment methods).
2. opens the shop page in a separate popup. This is good! But it would be still better if it would open in an external browser (due to issues with some payment methods).

The payment method issues I encountered so far:
- PayPal: if you want to pay with PayPal, the [Windows popup](https://i.imgur.com/hJuboot.png) opens and wants me to select an app to open the PayPal window with (but I can't select a browser or anything). In a browser it is correctly handled (a separate browser window opens to enter PayPal credentials). BUT: the API seems to open the login page in a browser nevertheless. So it is possible to make a payment which is recognized by the game, even though the client shop popup isn't aware and doesn't update (confirms the payment).
- Giropay: After entering the BIC, the same Windows popup shows up, but it DOESN'T open in the browser as well (like PayPal does) and renders this payment method useless.

I know that this issue is probably an underlying problem of the API and can't be fixed that easily. That's why I would suggest to put an URL handling exception for shop URLs to open in an external browser for now.

**Comment by kaiserdj** [comment]
First of all, thank you very much for the issue. Usually people don't give that much explanation, it helps a lot ..

I've been working this afternoon to find the best option and because the client core is electron (chrome wrapped). It is difficult to work with an external browser due to the fact that it does not share the cache or the cookies.

After several tests I have come to the conclusion that the best option is, when the client detects that a new window opens, check if it is the store. When the store opens, allow only that window (the store) to work like a normal browser but within the electron environment. So all windows can work with the same cache and cookies, and can work between them without any problem.

PS: I have only been able to test with the store, the accounts I have do not have a full uridium bank and I cannot test with that function ...

Any problem, suggestion, etc ... I will be happy to hear it and again thanks for the issue
